name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: before build
        run: |
          sudo apt-get install -y lib32stdc++6
          git submodule update --init
          wget -qO sourcemod.tar.gz "http://sourcemod.net/latest.php?os=linux&version=1.9"
          tar xfz sourcemod.tar.gz
          cp scripting/* addons/sourcemod/scripting/ -rf
          cp --remove-destination botmimic/scripting/* addons/sourcemod/scripting/ -rf
          cd addons/sourcemod/scripting/
          chmod +x spcomp
          PATH+=":$PWD"
          cd include
          wget https://raw.githubusercontent.com/splewis/csgo-pug-setup/master/scripting/include/pugsetup.inc
          wget https://raw.githubusercontent.com/splewis/get5/master/scripting/include/get5.inc
          git clone https://github.com/bcserv/smlib
          cp -r smlib/scripting/include/* .

      - name: build
        run: |
          cd addons/sourcemod/scripting
          ./compile.sh playercommands.sp
          ./compile.sh csutils.sp
          ./compile.sh botmimic.sp
        
      - uses: actions/upload-artifact@v2
        with:
          name: compiled
          path: addons/sourcemod/scripting/compiled/
